# Site settings
title: "HackerspaceSG: the Singapore tech scene's community centre"
email: contact@hackerspace.sg
description: > # this means to ignore newlines until "baseurl:"
  Singapore's first kiasu-free zone. The zouk of Geekdom!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackerspace.sg" # the base hostname & protocol for your site
twitter_username: hackerspacesg
github_username:  hackerspacesg

# Build settings
markdown: kramdown
